language: php

dist: 'precise'

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - ./vendor

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls -v
